2 css
MaxRazzhivin/purple-school-1 pull request #3
Opened 2024-03-02 10:46 UTC by MaxRazzhivin

2024-03-02 11:38 UTC, GitEsense requested changes
С таблицей решение конечно Ваше, но Вы ещё очень намучаетесь с ней, поэтому предлагаю переделать таблицы на элементы с блочным поведением и уже с ними работать (в том числе и как inline-block), тогда и структура будет проще, и работать будет с этим легче.

По стилям - необходимо переработать отступы и позиционирование, а так же размеры блоков.

в форме не доделано до конца, форма должна на 95% соответствовать макету (позиция, стили, фоны, шрифты, отступы, размеры)

Внесёте корректировки и сдавайте на повторную проверку.

2024-03-02 11:38 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +    height: 1516px;
Фиксированную высоту лучше убрать, иначе у нас контент может и не влезть, а вот ширину лучше указать через 
max-width, на случай, если у нас размер экрана меньше будет
Так же неплохо бы позиционировать (через margin: 0 auto), чтобы body блок был всегда по центру экрана и отступы слева  и справа были "равномерны"

2024-03-02 11:38 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +    padding: 9px 110px 12px 49px;
margin-bottom тут явно лишний, если мы хотим отступить от header - то отступаем от header, а не вложенного элемента внутри этого блока, а что касается box-sizing - его лучше вынести в самое начало документа в виде
```css
* {
   box-sizing: border-box;
}
```
Чтобы это применялось на все элементы документа, если не переопределено обратное

2024-03-02 11:38 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +}
вот такой марджин поведёт себя не очень приятно при изменении разрешения экрана, лучше предусмотреть динамический, либо указать для контента внутри "позиционировать в центре", например text-align: center;

2024-03-02 11:38 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +}
этот марджин для обёртки будет так же неудобен, лучше на таблицу положить "margin: 0 auto", чтобы она встала по центру

2024-03-02 11:38 UTC, GitEsense commented on puprle-school/1-Blog/index.html
>  <body style: width="1440" height="1516">
Вот этот инлайн стиль очень сильно попортит Вам кровушку, если Вы будете стилизовать через css и не будет понимания "а что не так", давайте стилизовать через css

2024-03-02 13:15 UTC, MaxRazzhivin commented
Вроде поправил, изменил таблицу на дивы, только с формой не понял что можно изменить, там только текст внутри отступы пришлось сделать меньше, чем в макете, потому что иначе обрезает его. В остальном вроде все как на макете - бордеры, ширина, высота.

2024-03-02 18:45 UTC, GitEsense requested changes
С блогом +- всё уже почти готово, осталось приляпать иконку на логотип и на поиск, плюс немного поправить ссылки на изображения и перепроверить отступы, переиспользования стилей ( убрать лишние теги типа height: auto), которые никак не влияют на код (в этом поможет devtool браузера), что же касается формы - она "собрана", но не стилизована, построен только "каркас", но нет стилизации фона листа, формы, её позиционирование, расположение и отступы элементов, их размеры и иконки (например на кнопке регистрации), вот как в макете
![image](https://github.com/MaxRazzhivin/purple-school-1/assets/101252030/fa6a624a-5f54-4616-863a-928eca409bac)

2024-03-02 18:45 UTC, GitEsense commented on puprle-school/1-Blog/index.html
> +            <img src="/puprle-school/1-Blog/Ellipse 1.png" width="50" height="50" alt="Аватарка автора">
ссылка ведёт в несуществующий каталог относительного пути, возможно её надо заменить на './Ellipse 1.png', т.к. она лежит в корне, а не "во вложенных папках"

2024-03-02 18:45 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +    margin: 0 auto;
Хорошо, но на само изображение хорошо бы наложить "border-radius" согласно макету

2024-03-02 18:45 UTC, GitEsense commented on puprle-school/2-Form/style.css
> +}
Это относится не в body скорее всего, а к самой форме, иначе мы не сможем положить форму в центр экрана, так же отсутствует background
```css
background: linear-gradient(225deg, #fdc5c5 25.45%, rgba(242, 152, 222, 0) 100%), linear-gradient(225deg, #ffa5a5 33.09%, rgba(255, 255, 255, 0) 82.34%), #f39494;
```

2024-03-06 14:59 UTC, GitEsense requested changes
Форма по прежнему без стилей - а надо бы стилизовать в соответствии с макетом
Макет
![image](https://github.com/MaxRazzhivin/purple-school-1/assets/101252030/1fe34544-9dff-493a-986d-c41fed243b69)

Ваша форма
![image](https://github.com/MaxRazzhivin/purple-school-1/assets/101252030/f17ac3e7-785e-47ae-8099-51c2e7526d24)

2024-03-06 14:59 UTC, GitEsense commented on puprle-school/1-Blog/index.html
> +                </label>
Лучше избавиться от статичных значений размера в самом img и задавать размеры через css, так поведение будет более ожидаемым (это не является ошибочным, но будет удобнее работать в одном пространстве), то же касается и изображений ниже

2024-03-06 14:59 UTC, GitEsense commented on puprle-school/1-Blog/index.html
> +            <img src="author-photo.png" width="50" height="50" alt="Аватарка автора" class="ava-photo">
либо изобретать верное поведение изображения "соответственно макету", либо использовать выгрузку "кругляша" и вложить его - на Ваш выбор (но тогда придётся это делать в рамках изучения flexbox и overflow: hidden

2024-03-10 16:15 UTC, GitEsense approved these changes
Вот теперь похоже на правду, можно очень много правок вносить и расписывать, но дальше будет изучение флексбокс, рекомендую сразу же пройти раздел "методологии и практики" и воспользоваться ими в рамках ДЗ по флексбокс

2024-03-10 16:15 UTC, GitEsense commented on puprle-school/2-Form/style.css
> +}
забыт border-radius, но ладно - на флексбоксах буду требовать 101% соответствия, сейчас хотя бы понимание есть и отлично
так же padding можно сразу указать как для верх \ низ, так и лево \ право, чтобы внутри не пришлось отступы марджином делать и спокойно воспользоваться 100% шириной (но к этому уже потом)

2024-03-10 16:15 UTC, GitEsense commented on puprle-school/2-Form/style.css
> +    background-color: rgba(243, 148, 148, 1);
```css
background: linear-gradient(
      225deg,
      #fdc5c5 25.45%,
      rgba(242, 152, 222, 0) 100%
    ),
    linear-gradient(225deg, #ffa5a5 33.09%, rgba(255, 255, 255, 0) 82.34%),
    #f39494;

2024-03-16 03:58 UTC, merged