3 flex
MaxRazzhivin/purple-school-1 pull request #4
Opened 2024-03-26 13:21 UTC by MaxRazzhivin

2024-03-27 08:55 UTC, GitEsense requested changes
Комментарии вложены, так же не стилизованы "тени", нет border-radius на некоторых элементах. Иными словами - если открыть макет и Ваш проект = они должны быть идентичны абсолютно на текущей стадии.
Во многих местах "display: flex" упрощает всё.

Так же в форме Фамилия и Имя не имеют отступа (а там 1px)

2024-03-27 08:55 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +    margin: 80px auto 77px;
Вот это очень опрометчиво и не нужно на body делать марджин сверху \ снизу, тут достаточно 0 auto

2024-03-27 08:55 UTC, GitEsense commented on puprle-school/1-Blog/style.css
>  }
Хорошо бы добавить align-items: center и можно добавить gap: 39px;
Тогда для 
```css
li:nth-child(1) {
    margin-right: 52px;
}
li:nth-child(2) {
    margin-right: 39px;
}
li:nth-child(3) {
    margin-right: 246px;
}
```

достаточно сделать просто 
```css
li:nth-child(1) {
    margin-right: 13px;
}

2024-03-27 08:55 UTC, GitEsense commented on puprle-school/1-Blog/style.css
>  .my-blog-pic {
Если хотите сделать марджин справа, то напишите margin-right: 11px
марджин для "top" категорически не нужен, во-первых - это вложенный span, а значит уже плохая практика, во-вторых, от кого и куда он должен отступать?

2024-03-27 08:55 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +}
с формой совершенно не понятно что творится, наверное надо всё-таки стилизовать саму форму и иконку вложить в неё ?)
те же padding выглядят несколько иначе, если посмотреть макет - мы увидим
padding: 9px 11px 12px 49px
вкладывать в лейбл не совсем верно будет
можно сделать разными вариантами, но стилизовать форму - некорректно, т.к. стилизуем мы именно инпут, а вот иконку можно через before вложить или отдельной картинкой и position absolute или через бекграунд

2024-03-28 07:25 UTC, MaxRazzhivin commented on puprle-school/1-Blog/style.css
> +    margin: 80px auto 77px;
Понял, поменял на padding-top: 80px для header и padding-bottom: 77px для footer. Надеюсь такое решение более правильное

2024-03-28 07:35 UTC, MaxRazzhivin commented on puprle-school/1-Blog/style.css
> +    margin: 80px auto 77px;
Касательно округлений и теней:
- нашел у буквы В на логотипе округление и тени. Правда теней на макете визуально не вижу вообще, не понял зачем они там в макете. Поставил на .my-blog-pic border-radius: 3px; и box-shadow: 0 15px 30px rgba(0, 0, 0, 0.15);
- округление добавил на главную картинку центральную в 5px;
- сделал вертикальные отступы у имени и фамилии автора блога по 1px (в фигме не показывало, может другие альтернативы нужны, чтобы детальнее посмотреть и измерить можно было).
- в надписи над статьей "FRONTEND 12 мая 2024" - какая-то серая точка между датой и словом Frontend. Радиусом 100px. Пытался сделать через обычный дефис и округлить его через border-radius, но ничего не вышло. В итоге нашел среди символов html и задал через &#149; Gap внутри установил как в макете на 12px. Всю строку сделал флексом и 3 элемента засунул в span. Надеюсь правильно, эта точка столько нервов сожрала.

2024-03-28 07:36 UTC, MaxRazzhivin commented on puprle-school/1-Blog/style.css
>  }
Все сделал, как написали, спасибо ) Я вроде и понимал головой, что отступы должны суммироваться, но видимо намудрил с приоритетами селекторов и у меня игнорировало margin-right отдельный. Сейчас все вышло.

2024-03-28 07:42 UTC, MaxRazzhivin commented on puprle-school/1-Blog/style.css
>  .my-blog-pic {
Исправил вроде, только у меня он был в .my-blog-pic, установил как написали margin-right: 11px;

2024-03-28 08:02 UTC, MaxRazzhivin commented on puprle-school/1-Blog/style.css
> +}
Вроде понял, надеюсь на это ) убрал вообще класс у формы. Лейбл вынес наружу и привязал через id к форме инпута. 
Обернул в div, поменял на отступы padding: 9px 11px 12px 49px
Картинку поиска через position absolute вставил в контейнер дива

2024-03-29 08:03 UTC, GitEsense approved these changes
Всё в целом хорошо, внесите правки, что оставил в конверсах и посмотрите что выйдет, посмотрите "почему так" и для Вас будет хорошим "подспорьем", внесёте правки - кидайте в мердж, на проверку уже сдавать не надо, ДЗ принято

2024-03-29 08:03 UTC, GitEsense commented on puprle-school/2-Form/form.html
> +                </div>
```html
                <div class="name-total">
                    <div class="forms-name1">
                        <input type="text" placeholder="Имя" name="name">
                    </div>
                    <div class="forms-name2">
                        <input type="text" placeholder="Фамилия" name="surname">
                    </div>
                </div>
```
я бы заменил на 
```html
<div class="name-total">
    <input type="text" placeholder="Имя" name="name">
    <input type="text" placeholder="Фамилия" name="surname">
</div>
```
а классы бы заменил так 
```css
input:not(input[type="checkbox"]) {
    padding: 9px 11px;
    background-color: rgba(245, 245, 245, 1);
    width: 100%;
    font-style: italic;
    font-size: 16px;
    line-height: 21.79px;
}
input:not[type="checkbox"]:focus{
    font-family: "Open Sans";
    font-weight: 600;
    font-style: normal;
}
```
Эти стили полностью закроют потребность в другой стилизации инпутов, но останется только одно
```css
.name-total input:first-child {
    border-radius: 5px 0 0 5px;
}
.name-total input:last-child {
    border-radius: 0 5px 5px 0;
}
```

А вот так можно стилизовать уже checkbox
```css
input[type='checkbox'] {
    opacity: 0;
}
input[type='checkbox']:checked + label[for='checkbox']::before {
    background-color: #089fe0;
    content: '✖';
    padding: 0 3px;
    color: white;
}
label[for='checkbox']::before {
    content: ' ';
    position: absolute;
    top: 0;
    left: 0;
    display: inline-block;
    margin: 2px;
    padding: 7px;
    border-radius: 5px;
    border: 1px solid #eeeeee;
    background-color: #f5f5f5;
    font-size: 11px;
}
```
Но и HTML придётся изменить на структуру
```html
<div class="policy">
   <input type="checkbox" name="checkbox" id="checkbox" />
   <label for="checkbox">Я прочитал и принимаю <a href="#">Условия пользования</a> </label>
</div>
```

Все остальные стили лейбл убрать и получится прям красота)

2024-03-29 09:30 UTC, MaxRazzhivin commented on puprle-school/1-Blog/style.css
> +}
Все сделал как описали, убрал блок обертку с хедера, перенес стили на него, только margin: 77px auto 69px вместо нуля по центру. Иначе он у меня смещается влево и снаружи центровка блока слетает.
Убрал из header-list margin-left: auto и добавил в header justify-content: space-between
Только не понял, зачем в header-list свойство flex:1. Помню вроде ставит занять всю ширину доступную, но у меня разницы визуально с ним и без него не увидел.

2024-03-29 09:32 UTC, MaxRazzhivin commented on puprle-school/2-Form/form.html
> +    <section class="form">
Понял, тогда оставлю лучше)

2024-03-29 09:51 UTC, MaxRazzhivin commented on puprle-school/2-Form/style.css
>  }
Действительно, увлекся кругом все во флексы помещать, убрал стиль .start-reg; text-align:center для формы вроде можно не ставить, так Флекс форма вся и стоит align-items: center; вроде по смыслу одинаковы они

2024-03-29 09:54 UTC, GitEsense commented on puprle-school/2-Form/style.css
> +}
> понял логично убрать тогда margin: 225px auto; так как смысл тот же самый с центровкой

Совершенно верно

> Добавил, посмотрел свойства, убрал несколько раз строку transform, но так и не понял почему без нее он просто в центр не ставит, и только с transform: translate (-50%, -50%); все становится на свои места

Суть проста
top: 50% = даёт отступ 50% сверху
left: 50% = даёт отступ 50% слева
 transform: translate (-50%, -50%) = смещает по оси "назад" X и Y на 50% от размера блока, тем самым компенсируя "занятое"

2024-03-29 09:54 UTC, MaxRazzhivin commented on puprle-school/2-Form/style.css
>      background-color: rgba(243, 148, 148, 1);
Благодарю) не увидел напрочь, когда-то может войдет в привычку тыкать по списку элементов в левой части, а не визуально по наитию своему

2024-03-29 09:55 UTC, GitEsense commented on puprle-school/1-Blog/style.css
> +}
> Помню вроде ставит занять всю ширину доступную, но у меня разницы визуально с ним и без него не увидел.

потому что с формы надо убрать margin-left: auto - именно он сейчас "занимает остаток", а так space-between делит равно (прижимая в начало и конец), margin - это компенсирует, но и flex: 1 выдаст для nav полностью - это два варианта реализации

2024-03-29 10:10 UTC, MaxRazzhivin commented on puprle-school/2-Form/form.html
> +                </div>
Все поставил как написали кроме чекбокса в конце, голова пока не вывозит, а слепо копировать-вставлять не хочется)

2024-03-29 10:14 UTC, GitEsense commented on puprle-school/2-Form/form.html
> +                </div>
> Все поставил как написали кроме чекбокса в конце, голова пока не вывозит, а слепо копировать-вставлять не хочется)

Для того и положил, чтобы изучили и посмотрели "почему так" и "зачем"

2024-03-29 10:17 UTC, MaxRazzhivin commented on puprle-school/2-Form/style.css
> +}
Ну вот ожидал уже после top и left по 50%, что отцентрует по логике, но он улетел дальше чем центр и вниз и вправо словно там было не 50, а 70%. И transform по идее думал должен на 50% значит назад в ноль возвращать на исходную позицию, но он как раз центрует словно отнимает 20%, если у первых смещений предположить, что было 70% относительно краев страницы.

2024-03-31 18:46 UTC, merged